### ISSUE TITLE
Properties lens doesn't like multi-line where first line has no value

### ISSUE THREAD

**Issue by gioppoluca** [hercules-team/augeas#224]
Like in this https://github.com/hercules-team/augeas/issues/110 the problem apply also to 1.0.0-7.el6

**Comment by domcleal** [comment]
This has been fixed in Augeas 1.2.0 as described the ticket.

Red Hat distribute an older version, so as I said in https://github.com/hercules-team/augeas/issues/110#issuecomment-41021392 you need to raise a support case or bugzilla there to change their EL6 package.  https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%206&component=augeas is a direct link to BZ.
