### ISSUE TITLE
test-put-symlink-augsave.sh failure

### ISSUE THREAD

**Issue by ggardella** [hercules-team/augeas#242]
I'm trying to figure out why this test is failing on my Sparc system. I get the failure mode:
   /etc/hosts.augsave has changed from the original /etc/hosts
The command which is being tested is the following:
   augtool --nostdinc -I $LENSES -r $ROOT --backup > /builds/ggardell/command.out <<EOF
   set /files/etc/hosts/1/alias myhost
   save
   EOF
Looking at the etc file and the backup, it looks like this command backs up the hosts file to hosts.augsave and then adds 'myhost' to the original:
   -bash-4.2$ cat hosts
   127.0.0.1 localhost foobar
   -bash-4.2$ cat hosts.augsave 
   127.0.0.1 localhost
Is this not expected? When I try to run by hand, I get the following error:
   $ augtool -nostdinc -I /builds/ggardell/userland/gate/components/augeas/augeas-1.3.0/lenses -r /builds
   /ggardell/userland/gate/components/augeas/build/sparcv9/build/test-put-symlink-augsave --backup > 
   /builds/ggardell/command.out <<EOF
   > set /files/etc/hosts/1/alias mynew
   > save
   > EOF
   /builds/ggardell/userland/gate/components/augeas/build/sparcv9/src/.libs/augtool: invalid option -- 'o'
   Usage: augtool [OPTIONS] [COMMAND]
   Load the Augeas tree and modify it. If no COMMAND is given, run interactively
   Run 'augtool help' to get a list of possible commands.

The test seems to indicate that the hosts and hosts.augsave should be identical. What am I missing here?

**Comment by lutter** [comment]
The test makes sure that an attacker can't make us write to an arbitrary place in the file system by making `hosts.augsave` a symlink there.

What it checks is that `/etc/hosts.augsave`, after augtool ran, is the same as `/etc/hosts` was before augtool ran; the change is merely there to force augeas to actually write changes to disk. The way the test checks whether these two files are equal is by using the `sum` command - I wonder if the test failure has to do with some differences in `sum` between Linux and Solaris. After running `test-put-symlink-augsave.sh` on my system (which passes), I get the following:

```
    > sum build/test-put-symlink-augsave/etc/hosts.augsave
    41839     1
```

Another possibility for the test failure might be some differences in how symlinks are handled - though I hope that's not the case.

Finally, the last `augtool` command in your comment fails because you passed `-nostdinc` rather than `--nostdinc` (missing another dash)

**Comment by ggardella** [comment]
Okay, I see now. I was missing the forest for the trees. The problem appears to be the result of the sum command.

If I look at the value of `$HOSTS_SUM`, I see:

    HOSTS_SUM =  1448 1 /builds/ggardell/userland/gate/components/augeas/build/sparcv9/build/test-put-symlink-augsave/etc/hosts

Somehow we are getting the value of `$HOSTS` included in the result. Likewise `$(sum $HOSTS_AUGSAVE)` includes the value of `$HOSTS_AUGSAVE`. While the numeric value at the begging matches, the whole value will never match.

This appears to be a quirk of our Solaris sum binary. If I fully qualify `/usr/gnu/bin/sum` in the script it works. How do you recommend we address this?

**Comment by lutter** [comment]
Since we really only care about the checksum, it's probably best to replace `$(sum $HOSTS)` with `$(sum $HOSTS | cut -d ' ' -f 1)` or some such. Of course, that needs to happen everywhere where sum is called.

**Comment by ggardella** [comment]
I had done similar with `| awk '{print $1}'` (which passed). I just tested with ` | cut -d ' ' -f 1` and the test now passes.

**Comment by ggardella** [comment]
I have created a pull request with the above fix.
