### ISSUE TITLE
On OSX libedit lacks rl_crlf and rl_replace_line

### ISSUE THREAD

**Issue by lutter** [hercules-team/augeas#256]
On OSX, readline isn't available by default; instead, augtool gets linked against libedit. That is missing a few functions (rl_crlf and rl_replace_line) which need to be handled in the code similar to how rl_completion_matches is handled

**Comment by dtrebbien** [comment]
One way of working around this issue is to install the [Homebrew](http://brew.sh) readline package and then run `./autogen.sh` with the following environment variables set:

<pre>
CPPFLAGS=-I/usr/local/opt/readline/include
LDFLAGS=-L/usr/local/opt/readline/lib
</pre>

(tested Mac OS X 'El Capitan' version 10.11.1)

I think that this approach is preferable to adding replacements (PR #257) because readline would actually be used instead of the BSD libedit library.

**Comment by lutter** [comment]
This workaround wouldn't keep you from using the Homebrew libraries though, right ? I.e., even with this patch committed, if you do what you said above you would get a fully functional readline, right ?

The reason why I'd like to commit this is that the buildsystem where this became an issue doesn't have the Homebrew readline AFAIK.

**Comment by dtrebbien** [comment]
> This workaround wouldn't keep you from using the Homebrew libraries though, right ? I.e., even with this patch committed, if you do what you said above you would get a fully functional readline, right ?

Yes, you are right.

> The reason why I'd like to commit this is that the buildsystem where this became an issue doesn't have the Homebrew readline AFAIK.

Ah, I see.
