### ISSUE TITLE
support for negative values in chrony lens

### ISSUE THREAD

**Issue by mwasilew2** [hercules-team/augeas#347]
augtool 1.4.0, centos 1511, parsing chrony.conf fails due to a negative number for makestep. Negative values are used as described in: https://docs.fedoraproject.org/en-US/Fedora/18/html/System_Administrators_Guide/sect-Understanding_the_chrony_configuration_commands.html

**Comment by domcleal** [comment]
Thanks for the report, I believe this has been fixed in https://github.com/hercules-team/augeas/commit/664f8a8d690f3cfac2d3a8b44834d809e15b51ed (no release yet).

If you need a fix to CentOS then you'll need to open a bug against RHEL's augeas component at bugzilla.redhat.com and it may be backported in a future release.
