### ISSUE TITLE
regex "multiple any or newline class" does not match multiline comments

### ISSUE THREAD

**Issue by MatthewHannigan** [hercules-team/augeas#394]
In _augtool_, I expected this regex `"[.\\n]*"` to match a multline comment in xml, however it doesn't.
This regexp `"(\\n|.)*"` works.
Via irc @domcleal , 

> I can't see why it isn't working with [], but using \n outside that does work, e.g. regexp("(.*\\n?.*)*")
> ... or remove the ? to match only multi-line

**NOTE** regexp may be scrambled by github markdown/editor.  View source to see the real thing.

I have only tested with xml; and only with augtool but I presume the glitch deeper within augeas and is not confined to augtool or xml. (but remove one of the sloshes if not using _augtool_)

**Comment by MatthewHannigan** [comment]
A shell script to demo various regexps that I have tried.

```shell
# augtool
# can't match multiline and single line with []

set -u
set -e

tmpdir=$(mktemp -d)
trap 'rm -r $tmpdir' 0
echo '
<top>
    <!-- single line comment -->
    <!-- multiline
        comment
    -->
</top>
' > $tmpdir/somefile.xml

echo '
transform Xml incl somefile.xml
load
# does not match multiline - bug?
match /files/somefile.xml/top/#comment[. =~ regexp("[.\\n]*")]
# works from Dominic
match /files/somefile.xml/top/#comment[. =~ regexp("(.*\\n?.*)*")]
# works and is smaller
match /files/somefile.xml/top/#comment[. =~ regexp("(.|\\n)*")]
# does not match but I expected it to match
match /files/somefile.xml/top/#comment[. =~ regexp("[.\\r\\n]*")]
# does not match multiline - expected, since . does not match newline
match /files/somefile.xml/top/#comment[. =~ regexp(".*")]
' >$tmpdir/glitch.aug

cat $tmpdir/glitch.aug | augtool -r $tmpdir -L -A
```

**Comment by lutter** [comment]
I think the mystery is that the regexp syntax does not recognize any special characters inside character classes `[..]` - anything in there is taken literally with the exception of ranges like `[a-z]` which expand to what you'd think they do.

There's an added wrinkle in that both the reader for augtool and the `regexp` function unescape escaped characters like `\n`, so that when you write either `regexp("\n")` or `regex("\\n")` the string from which a regexp is ultimately constructed contains a newline character.

To add to all that, there's also a bug in `unescape` in `internal.c` in that it doesn't recognize `\\` as an escape sequence for a backslash character, so that when you write `regexp("\\n")`, that gets unescaped into a string consisting of a backslash and a newline character.

The long and short of it is that if you want to match any character, you should use `regexp("(.|\\n)*")`

**Comment by MatthewHannigan** [comment]
OK, looks like it was just me not fully understanding [] in the regexes, in particular that the special chars are not special.
