### ISSUE TITLE
Span indices not updated

### ISSUE THREAD

**Issue by bmw** [hercules-team/augeas#467]
I created the same setup as I posted in #466 except `commands` is:
```
transform Httpd incl /home/bmw/default.conf
load
span /files/home/bmw/default.conf/VirtualHost[2]
set /files/home/bmw/default.conf/VirtualHost[2]/directive[last() + 1] foo
save
print /files/home/bmw/default.conf/VirtualHost[2]
span /files/home/bmw/default.conf/VirtualHost[2]
```
Running `augtool -f commands -I augeas_lens/ -L --span` from this directory you can see that the result of `span` isn't updated after the file is modified. I saw this behavior in both Augeas 1.4 and 1.7.

**Comment by lutter** [comment]
Yes, spans are only calculated when files are loaded. One simple way to avoid this issue is to force reloading of the file with something like
```
rm /files/home/bmw/default.conf
load
```

The `rm` is necessary since Augeas tries to avoid loading files it already has in memory that haven't changed since the last time it did anything with them. It won't modify the file, it just forces Augeas to load it.

I'll try and come up with a solution that recalculates span info on save though, too.
