### ISSUE TITLE
bug in libfa

### ISSUE THREAD

**Issue by pierreganty** [hercules-team/augeas#518]
`./fadot -o complement "(.|\n)*"` returns `.*\n(.|\n)*`
This is not correct since the complement of `(.|\n)*` is the empty set.

**Comment by lutter** [comment]
There's no bug - just that fadot does not interpret escape sequences; the regexp you pass in is identical to `(.|n)*`, i.e. `.*` and the result indeed says "any string that contains at least one newline" which is the correct complement. The regular expression parser does strip the `\` as that can be used to remove special meaning from characters, like `.` or `|`.

I strongly recommend using the [ruby-fa](https://github.com/lutter/ruby-fa) bindings instead of fadot for more finicky explorations involving control characters etc.
