### ISSUE TITLE
output of fadot leads to confusion

### ISSUE THREAD

**Issue by pierreganty** [hercules-team/augeas#519]
The empty set (or empty language) can be expressed as the intersection of a set and its complement. For insance `p` and its complement:
`./fadot -o complement "p"` returns `(p(.|\n)|[^p])(.|\n)*|()` and then
`./fadot -o intersect "(p(.|\n)|[^p])(.|\n)*|()" "p"`
which returns a blank line exactly as `./fadot -o show ""` and `./fadot -o show "()"` do.
So from the command line point of view the output of the three commands is the same.
Now let us have a look at the automata (using the `-f` option). 
For `""` and `"()"` the automaton accepts the empty string (i.e. epsilon) while for 
`intersect "(p(.|\n)|[^p])(.|\n)*|()" "p"` the language accepted is the empty set (it has no accepting states).

PS: This is a great tool you have there.

**Comment by lutter** [comment]
Thanks for the compliments !

As I said in the other comment, I strongly recommend using [ruby-fa](https://github.com/lutter/ruby-fa) for more serious explorations, simply because it gives you way more control than fadot ever could - in fact, the reason I wrote them recently was exactly because I got fed up dealing with doing that from the command line.

I'd consider fadot more of an example of how to use the libfa API than anything you could do serious work with (did I mention ruby-fa ? ;)

I'll close this since I don't think I will have time to improve fadot, but I'd totally review/merge pull requests to make fadot better.
