### ISSUE TITLE
sshd lense multiple parameters not corrected

### ISSUE THREAD

**Issue by aoe-mak** [hercules-team/augeas#528]
Hey,

the /etc/ssh/sshd_config will not be updated when I have more than one parameter defined.

I have:
```
augtool> print /files/etc/ssh/sshd_config/PasswordAuthentication
/files/etc/ssh/sshd_config/PasswordAuthentication[1] = "yes"
/files/etc/ssh/sshd_config/PasswordAuthentication[2] = "yes"
```

I do:
```
augtool> set /files/etc/ssh/sshd_config/PermitRootLogin no
augtool> save
augtool> errors
augtool>
```

I tried:
```
augtool> setm /files/etc/ssh/sshd_config/PermitRootLogin no
augtool> save
error: Failed to execute command
saving failed (run 'errors' for details)
augtool>
```

We use Puppet (JFYI):
```
Debug: Augeas[Disable root access](provider=augeas): Opening augeas with root /, lens path , flags 32
Debug: Augeas[Disable root access](provider=augeas): Augeas version 1.4.0 is installed
Debug: Augeas[Disable root access](provider=augeas): Will attempt to save and only run if files changed
Debug: Augeas[Disable root access](provider=augeas): sending command 'set' with params ["/files/etc/ssh/sshd_config/PasswordAuthentication", "no"]
Debug: Augeas[Disable root access](provider=augeas): Skipping because no files were changed
Debug: Augeas[Disable root access](provider=augeas): Closed the augeas connection
```

I would expect that Augeas would change all the options. I mean there is a lense, and should Augeas not understand that this option can only be there one time and should in that case update all of them?

I read/skimmed a lot (JFYI) but maybe I missed some important info.
https://puppet.com/docs/puppet/5.3/resources_augeas.html#sshdconfig
http://augeas.net/faq.html
https://github.com/hercules-team/augeas/wiki/List-of-frequent-errors
https://github.com/hercules-team/augeas/wiki/Tracking-down-errors
https://github.com/hercules-team/augeas/wiki/Debugging-tips
https://github.com/hercules-team/augeas/issues/206

Cheers

**Comment by lutter** [comment]
Hi,

first off, it seems in your example you are switching between `PasswordAuthentication` and `PermitRootLogin`. Unfortunately, Augeas does not know that specifying `PasswordAuthentication` in an sshd config file makes no sense and that it should really change multiple instances of it.

If you want to make sure all of them get changed in unison, you'd use (check `augtool help setm` for details)
```
    setm /files/etc/ssh/sshd_config PasswordAuthentication no
```

Alternatively, you could get rid of the duplicates and then just use `set`. If all you want to keep is the first `PasswordAuthentication`, you would get rid of the rest with
```
    rm /files/etc/ssh/sshd_config/PasswordAuthentication[position() != 1]
    set /files/etc/ssh/sshd_config/PasswordAuthentication no
```

I'll close this issue since it's not really a bug in Augeas. Let me know if there is anything else I could help with.
