### ISSUE TITLE
Build without docs, examples, manuals, and tests

### ISSUE THREAD

**Issue by joerg-krause** [hercules-team/augeas#535]
Build systems like [Buildroot](https://buildroot.org) target small embedded systems where it is preferable to not build the docs, examples, manuals, and tests. Most autoconf-based programs offer a configure option like `--disable-docs`, `--disable-tests`, etc. Would be great if augeas has these options, too :smile:.

**Comment by lutter** [comment]
The typical `make && make install` should not build or run any tests, only `make check` does that. Similarly, docs are generated using NaturalDocs - if that is not available, docs are not generated either.

IOW, there shouldn't be a need for adding switches to `configure` to suppress that. Are there things that cause trouble when trying to build augeas with buildroot ? More than happy to try and address any issues you encounter, but I'd need to know what specifically they are.

**Comment by joerg-krause** [comment]
There is an issue building the *dump* example with Buildroot. Buildroot uses a patched version of *libtool* to fix some cross-compilation issues, e.g. preventing linkage with libraries in `-L/usr/lib`.

Building the `dump` example fails with:
```
/arm-linux-gnueabihf/bin/ld: attempted static link of dynamic object `../src/.libs/libaugeas.so'
```

Not sure, why it is trying to link with the shared library, but it is working when building with the unpatched *libtool*.

As Buildroot does not install examples and tests (the augeas tests binaries are ~1.4MB) they are removed in a hook.

**Comment by lutter** [comment]
Is this happening with the released augeas-1.9.0 tarball or from git HEAD ? The 1.9.0 release had a `examples/Makefile.am` with a couple of problems (at least one of which you fixed ;).

I just noticed that that Makefile.am still has `dump_LDFLAGS = -static` in it, which might be to blame for the failure you are seeing - it's a leftover from when I was testing things with it. If you are set up for that (i.e., can easily build from git HEAD), could you try what happens if we get rid of that flag ? If that doesn't do the trick, there's always the big hammer of adding a `--without-examples` to configure, though I'd prefer if we can make it just work.

**Comment by joerg-krause** [comment]
Removing `dump_LDFLAGS = -static` works :smile:

**Comment by lutter** [comment]
Awesome ! Committed the fix. Thanks for trying it out - at some point, I would love to hear what you are doing with Augeas in an embedded context ...

**Comment by joerg-krause** [comment]
I am using augeas because I was looking for a sane way of allowing users to change device configurations like static network settings via remote control.

**Comment by lutter** [comment]
Neat ! I hope it works out well for you. A long time ago, I wrote [netcf](https://pagure.io/netcf) which provides an API for changing network config files and uses Augeas under the hood (it's also what libvirt uses for managing network interfaces) Not sure if that's useful for you situation, but might be worth a look.
